### ISSUE TITLE
FFI Build for Android : expected `u8`, found `i8`

### ISSUE THREAD

**Issue by aloisdeniel** [y-crdt/y-crdt#246]
Hey!

I'm trying to bind the library to Flutter, and so to build the native libraries for iOS, Android and macOS (for now).

For iOS everything went fine, but I'm hitting an error when building the Android library : 

```
TYPE_REFS_ARRAY => Y_ARRAY,
     |                                ^^^^^^^ expected `u8`, found `i8`
```

![image](https://user-images.githubusercontent.com/7687231/213867377-72544823-6b32-462b-93ba-b89805455a6d.png)

I'm no Rust expert, but it seems that the i8 type isn't available for all target architectures.

I'm using these command lines for building the project with the NDK :

```bash
    # Defining NDK root directory
    NDK_VERSION="25.1.8937393"
    NDK=${ANDROID_NDK_HOME:-${ANDROID_NDK_ROOT:-"$ANDROID_SDK_ROOT/ndk/$NDK_VERSION"}}
    COMPILER_DIR="$NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin"
    export PATH="$COMPILER_DIR:$PATH"
    echo "$COMPILER_DIR"

    # Binding arch-specific NDK compilers to cargo
    export CC_i686_linux_android=$COMPILER_DIR/i686-linux-android21-clang
    export AR_i686_linux_android=$COMPILER_DIR/llvm-ar
    export CARGO_TARGET_I686_LINUX_ANDROID_LINKER=$COMPILER_DIR/i686-linux-android21-clang
    export CARGO_TARGET_I686_LINUX_ANDROID_AR=$COMPILER_DIR/llvm-ar

    export CC_x86_64_linux_android=$COMPILER_DIR/x86_64-linux-android21-clang
    export AR_x86_64_linux_android=$COMPILER_DIR/llvm-ar
    export CARGO_TARGET_X86_64_LINUX_ANDROID_LINKER=$COMPILER_DIR/x86_64-linux-android21-clang
    export CARGO_TARGET_X86_64_LINUX_ANDROID_AR=$COMPILER_DIR/llvm-ar

    export CC_armv7_linux_androideabi=$COMPILER_DIR/armv7a-linux-androideabi21-clang
    export AR_armv7_linux_androideabi=$COMPILER_DIR/llvm-ar
    export CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER=$COMPILER_DIR/armv7a-linux-androideabi21-clang
    export CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_AR=$COMPILER_DIR/llvm-ar

    export CC_aarch64_linux_android=$COMPILER_DIR/aarch64-linux-android21-clang
    export AR_aarch64_linux_android=$COMPILER_DIR/llvm-ar
    export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$COMPILER_DIR/aarch64-linux-android21-clang
    export CARGO_TARGET_AARCH64_LINUX_ANDROID_AR=$COMPILER_DIR/llvm-ar

    rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
    
    cargo build --target armv7-linux-androideabi --release
    cp target/armv7-linux-androideabi/release/libyrs.a ../ydart/android/src/main/jniLibs/armv7/libyrs.a
    
    cargo build --target i686-linux-android--release
    cp target/i686-linux-android/release/libyrs.a ../ydart/android/src/main/jniLibs/i686/libyrs.a
    
    cargo build --target x86_64-linux-android --release
    cp target/x86_64-linux-android/release/libyrs.a ../ydart/android/src/main/jniLibs/x86_64/libyrs.a

    cargo build --target aarch64-linux-android --release
    cp target/aarch64-linux-android/release/libyrs.a ../ydart/android/src/main/jniLibs/aarch64/libyrs.a
    exit 0
```

Here is my update `Cargo.toml file : 

```toml
[package]
name = "yffi"
version = "0.15.0"
authors = ["Aloïs Deniel <adeniel@clickup.com>", "Kevin Jahns <kevin.jahns@protonmail.com>","Bartosz Sypytkowski <b.sypytkowski@gmail.com>"]
keywords = ["crdt", "c-ffi", "yrs"]
edition = "2018"
license = "MIT"
description = "Bindings for the Yrs native C foreign function interface"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib0 = { git = "https://github.com/y-crdt/y-crdt/", version = "0.15.0" } 
yrs = { git = "https://github.com/y-crdt/y-crdt/", version = "0.15.0" } 
rand = "0.7.0"

[lib]
crate-type = ["staticlib", "dylib"]
name = "yrs"

[profile.release]
strip = true
```

Thanks
